version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: wp_db
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wp_app
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: wp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/letsencrypt:ro
    depends_on:
      - wordpress

  acme-companion:
    image: nginxproxy/acme-companion
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./wordpress:/usr/share/nginx/html
    environment:
      DEFAULT_EMAIL: ${LETSENCRYPT_EMAIL}
